apiVersion: v1
kind: Pod
metadata:
  name: adapter
  namespace: default
spec:
  containers:
  - image: redis
    name: redis

  # Prometheus interface.
  - image: oliver006/redis_exporter
    name: adapter